{% set name = "jump" %}
{% set version = "0.5" %}
{% set sha256 = "ae07175784eb00c4be2e3f4d9e5454a5dfbe83087972e6e7a3a9f717665c7400" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/olllom/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - jump = jump.jump:main

requirements:
  host:
    - python >=3.5
    - setuptools >=0.7
    - plumbum
    - pip
    - click >=6.0

  run:
    - python >=3.5
    - plumbum >=1.5
    - click >=6.0

test:
  imports:
    - jump
  commands:
    - jump --help

about:
  home: https://github.com/Olllom/jump
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Running remote jupyter notebooks in a local browser window.'

extra:
  recipe-maintainers:
    - Olllom
    - wiso
